# Generated by Django 2.1 on 2018-08-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host_info',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('remote_port', models.IntegerField()),
                ('os_type', models.CharField(max_length=100)),
                ('db_type', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=200)),
            ],
        ),
    ]
