# Generated by Django 2.1 on 2018-08-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unifieddbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='database_info',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=200)),
                ('db_port', models.IntegerField()),
                ('db_version', models.CharField(max_length=200)),
                ('db_edition', models.CharField(max_length=200)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unifieddbms.host_info')),
            ],
        ),
    ]
